apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-eu-

resources:
- ../../base

components:
  - ../../variants/prod
  - ../../variants/eu
  - ../../variants/gpu

patchesStrategicMerge:
- environment.yml
- replicas.yml

