apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: load
namePrefix: load-non-gpu-

resources:
- ../../base

components:
  - ../../variants/non-prod
  - ../../variants/non-gpu

patchesStrategicMerge:
- environment.yml
- replicas.yml

