apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-us-

resources:
- ../../base

components:
  - ../../variants/prod
  - ../../variants/us
  - ../../variants/gpu

patchesStrategicMerge:
- environment.yml
- replicas.yml

