apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: staging-us-

resources:
- ../../base

components:
  - ../../variants/non-prod
  - ../../variants/us
  - ../../variants/gpu

patchesStrategicMerge:
- environment.yml
- replicas.yml

